[versions]
kotlin = "2.1.0"
junit-jupiter = "5.10.3"
guava = "33.3.1-jre"

[libraries]
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-jupiter" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
